### ISSUE TITLE
Javascript reported as not available

### ISSUE THREAD

**Issue by ferdinandyb** [gmurdocca/elinks-seamonkey#1]
When I run this image, elinks itself says it has ecmascript enabled, but when I tried to access MS login page it reported JS is not enabled. I also checked on this page: 

https://www.whatismybrowser.com/detect/is-javascript-enabled

it also reports that JS is not available. I am doing something wrong? Can I do anything to make this work?

**Comment by gmurdocca** [comment]
Hi @ferdinandyb
Unfortunately I experienced the same for many sites that required JS. JS support in eLinks is known to be limited, as the [referenced article](https://www.cnx-software.com/2014/02/09/building-elinks-text-based-web-browser-with-some-sort-of-javascript-support/) states "Bear in mind that the implementation is far from complete, and most pages won’t work, at least for now".

**Comment by ferdinandyb** [comment]
Thanks for confirming! Browsing is very unfortunately moving towards chromium being the only fully working alternative and almost impossible to start from scratch ...
